project_id = "nhkywhrptamtbsnrevtc"

[functions.upload-document]
verify_jwt = true

[functions.archie-chat]
verify_jwt = false

[functions.scrape-website]
verify_jwt = true

[functions.send-insights-email]
verify_jwt = false